contas_casa/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('source.urls'))
] 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

source/urls.py
from django.urls import path
from django.conf import settings
from . import views

urlpatterns = [
    path('', views.pagina_principal, name='pagina_principal'),
    path('pessoas/', views.pessoas, name='pessoas'),
    path('pessoas/<int:pessoa_id>/rendas', views.pessoa_rendas, name='pessoa_rendas'),
    path('propriedades/', views.propriedades, name='propriedades'),
    path('propriedades/<int:id_propriedade>', views.propriedade, name='propriedade'),
    # path('metas/', views.metas, name='metas'),
    # path('categorias/', views.categorias, name='categorias'),
    path('despesas', views.despesas, name='despesas'),
    path('despesas/criar', views.despesa_criar, name='despesa_criar'),
    path('despesas/<int:despesa_id>/pagamentos', views.despesa_pagamentos, name='despesa_pagamentos'),
    path('despesas/<int:despesa_id>/pagar', views.despesa_pagar, name='despesa_pagar'),
    # path('rendas/', views.rendas, name='rendas'),
]

source/models.py
from django.db import models


class Pessoa(models.Model):
    nome = models.CharField(max_length=50)
    saldo = models.DecimalField(max_digits=15, decimal_places=2, default=0)
    nascimento = models.DateField(null=True, blank=True)

    def __str__(self):
        return self.nome

    def nascimento_padrao(self) -> str:
        return '-'.join(reversed(str(self.nascimento).split('/')))
    
    def saldo_formatado(self) -> str:
        return f'{self.saldo:,.2f}'.replace(',', 'X').replace('.', ',').replace('X', '.')


class Propriedade(models.Model):
    nome = models.CharField(max_length=50)
    descricao = models.TextField(max_length=75, null=True)
    imagem = models.ImageField(upload_to='propriedades', null=True);
    pessoas = models.ManyToManyField(Pessoa)

    def __str__(self):
        return self.nome


class Renda(models.Model):
    nome = models.CharField(max_length=100)
    pessoa = models.ForeignKey(Pessoa, on_delete=models.CASCADE)
    valor = models.DecimalField(max_digits=15, decimal_places=2)
    data = models.DateField()

    def __str__(self):
        return f'{self.nome} - {self.pessoa} - R${self.valor}'


class Meta(models.Model):
    nome = models.CharField(max_length=100)
    propriedade = models.ForeignKey(Propriedade, on_delete=models.CASCADE, null=True, blank=True)
    pessoa = models.ForeignKey(Pessoa, on_delete=models.CASCADE, null=True, blank=True)
    valor = models.DecimalField(max_digits=15, decimal_places=2)
    saldo = models.DecimalField(max_digits=15, decimal_places=2, default=0)
    descricao = models.TextField(max_length=255, null=True, blank=True)
    data_final = models.DateField(null=True, blank=True)

    def __str__(self):
        return f'{self.nome} - R${self.saldo}/R${self.valor}'


class Categoria(models.Model):
    nome = models.CharField(max_length=50)
    descricao = models.TextField(max_length=255, null=True, blank=True)
    cor = models.CharField(max_length=7)  # #FFFFFF

    def __str__(self):
        return self.nome


class Parcelamento(models.Model):
    nome = models.CharFieldnome = models.CharField(max_length=100)
    propriedade = models.ForeignKey(Propriedade, on_delete=models.CASCADE)
    descricao = models.TextField(max_length=255, null=True, blank=True)
    data = models.DateTimeField() 

    def __str__(self):
        return self.name


class Despesa(models.Model):
    nome = models.CharField(max_length=100)
    # criador = models.ForeignKey(Pessoa, on_delete=models.CASCADE, null=True, blank=True) 
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE) 
    propriedade = models.ForeignKey(Propriedade, on_delete=models.CASCADE, null=True, blank=True)
    meta = models.ForeignKey(Meta, on_delete=models.CASCADE, null=True, blank=True)
    parcelamento = models.ForeignKey(Parcelamento, on_delete=models.CASCADE, null=True, blank=True)
    valor = models.DecimalField(max_digits=15, decimal_places=2)
    data_criacao = models.DateField(auto_now_add=True)
    data_vencimento = models.DateField(null=True, blank=True)

    def __str__(self) -> str:
        return f'{self.nome} - R${self.valor}'

    def valor_pendente(self) -> float:
        return self.valor - sum([pagamento.valor for pagamento in self.pagamento_set.all()])

    def somar_valores(despesas) -> float:
        return sum([despesa.valor for despesa in despesas])

    def somar_pagamentos(despesas) -> float:
        return sum([pagamento.valor for despesa in despesas for pagamento in despesa.pagamento_set.all()])


class Pagamento(models.Model):
    # Payment Methods
    PAYMENT_METHODS = {
        "CC": "Cartão de Crédito",
        "CD": "Cartão de Débito",
        "PX": "PIX",
        "CA": "Cartão Alimentação",
        "DI": "Dinheiro"
    }

    despesa = models.ForeignKey(Despesa, on_delete=models.CASCADE)
    pessoa = models.ForeignKey(Pessoa, on_delete=models.CASCADE)
    valor = models.DecimalField(max_digits=15, decimal_places=2)
    forma_pagamento = models.CharField(max_length=2, choices=PAYMENT_METHODS)
    descricao = models.TextField(max_length=255, null=True, blank=True)
    data = models.DateField()

    def __str__(self):
        return f'{self.pessoa} - {self.despesa} - R${self.valor}'
    

source/views.py
from django.shortcuts import render, redirect, HttpResponse, get_object_or_404
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from django.template.loader import render_to_string
from django.contrib import messages
from django.db import transaction
from .models import Pessoa, Propriedade, Despesa, Categoria, Pagamento
from datetime import datetime
from decimal import Decimal
import json


# Create your views here.
def pagina_principal(request):
    return render(request, template_name='pagina_principal.html')


def pessoas(request):
    pessoas = Pessoa.objects.all()
    return render(request, template_name='pessoas.html', context={'pessoas': pessoas})


def propriedades(request):
    propriedades = Propriedade.objects.all()
    return render(request, template_name='propriedades.html', context={'propriedades': propriedades})


def propriedade(request, id_propriedade: int):
    request.session['id_propriedade'] = id_propriedade
    propriedade = Propriedade.objects.get(id=id_propriedade)
    return render(request, template_name='propriedade.html', context={'propriedade': propriedade})


def despesas(request):
    id_propriedade = request.session.get('id_propriedade')
    if not id_propriedade:
        return redirect('propriedades')

    categorias = Categoria.objects.all()
    despesas = Despesa.objects.all().filter(propriedade=id_propriedade).order_by('-data_criacao', '-id')
    gasto = Despesa.somar_valores(despesas)
    pago = Despesa.somar_pagamentos(despesas)
    pendente = gasto - pago
    
    context = {
        'categorias': categorias, 
        'despesas': despesas,
        'hoje': datetime.today().date,
        'gasto': gasto,
        'pago': pago,
        'pendente': pendente
    }

    return render(request, template_name='despesas.html', context=context)


def despesa_criar(request):
    if request.method == 'GET':
        hoje = datetime.today().strftime('%Y-%m-%d')
        categorias = Categoria.objects.all()
        pessoas = Propriedade.objects.get(id=request.session['id_propriedade']).pessoas.all()
        formas_pagamento = Pagamento.PAYMENT_METHODS

        context = {
            'hoje': hoje,
            'categorias': categorias,
            'pessoas': pessoas,
            'formas_pagamento': formas_pagamento 
        }

        return render(request, template_name='despesa_criar.html', context=context)
    
    elif request.method == 'POST':
        try:
            despesa = Despesa(
                propriedade=Propriedade.objects.get(id=request.session.get('id_propriedade')),
                nome=request.POST.get('nome'),
                categoria=Categoria.objects.get(id=request.POST.get('categoria')),
                valor=request.POST.get('valor'),
                data_vencimento=datetime.strptime(request.POST.get('vencimento', ''), '%Y-%m-%d')
            )
            despesa.save()
            messages.success(request, 'Despesa criada com sucesso!')
        except Exception as error:
            messages.error(request, f'Ocorreu um erro ao criar a despesa:\n{error}')

        if request.POST.get('pagamento', 'false') == 'true':
            try:
                pessoa = Pessoa.objects.get(id=request.POST.get('pessoa'))
                valor = request.POST.get('valor')

                pagamento = Pagamento(
                    despesa=despesa,
                    pessoa=pessoa,
                    valor=valor,
                    forma_pagamento=request.POST.get('forma_pagamento'),
                    descricao='Pagamento Automático',
                    data=datetime.now()
                )
                pagamento.save()

                pessoa.saldo -= Decimal(valor)
                pessoa.save()

                messages.success(request, 'Pagamento realizado com sucesso!')
                
            except Exception as error:
                messages.error(request, f'Ocorreu um erro ao tentar realizar o pagamento da despesa:\n{error}')
        else:
            messages.error(request, f'Não foi registrado pagamento para a despesa')

        return redirect('despesa_criar')


def despesa_pagamentos(request, despesa_id: int):
    despesa = get_object_or_404(Despesa, id=despesa_id)

    pagamentos = despesa.pagamento_set.all().order_by('-data', '-valor')
    valor_pendente = despesa.valor_pendente()

    context = {
        'despesa_id': despesa.id,
        'pagamentos': pagamentos,
        'valor_pendente': valor_pendente,
        'valor_pendente_str': str(valor_pendente)
    }
    
    if valor_pendente > 0:
        context['categorias'] = Categoria.objects.all()
        context['pessoas'] = Propriedade.objects.get(id=request.session['id_propriedade']).pessoas.all()
        context['formas_pagamento'] = Pagamento.PAYMENT_METHODS
        context['hoje'] = datetime.today().strftime('%Y-%m-%d')

    pagamentos_html = render_to_string('despesa_pagamentos.html', context=context, request=request)

    return JsonResponse(pagamentos_html, safe=False)


@require_POST
def despesa_pagar(request, despesa_id: int):
    try:
        body = json.loads(request.body.decode('utf-8'))

        valor           = body.get('valor')
        forma_pagamento = body.get('forma_pagamento')
        descricao       = body.get('descricao')
        pessoa_id       = body.get('pessoa')
        data_str        = body.get('data')

        despesa         = get_object_or_404(Despesa, id=despesa_id)
        pessoa          = get_object_or_404(Pessoa, id=pessoa_id)
        data            = datetime.strptime(data_str, '%Y-%m-%d')

        with transaction.atomic():
            pagamento = Pagamento(
                despesa=despesa,
                pessoa=pessoa,
                valor=valor,
                forma_pagamento=forma_pagamento,
                descricao=descricao,
                data=data
            )
            pagamento.save()

            pessoa.saldo -= Decimal(valor)
            pessoa.save()

        return HttpResponse(status=201)
    
    except Exception as erro:
        print(erro)
        return HttpResponse(status=400)


def pessoa_rendas(request, pessoa_id: int):
    pessoa = get_object_or_404(Pessoa, id=pessoa_id)

    rendas = pessoa.renda_set.all().order_by('-data', '-valor')

    context = {
        'pessoa_id': pessoa.id,
        'rendas': rendas,
    }

    if request.method == "GET":
        return render(request=request, template_name='components/modal_rendas.html', context=context)
    else:
        rendas_html = render_to_string('components/modal_rendas.html', context=context, request=request)
        return JsonResponse(rendas_html, safe=False)


def pessoa_adicionar_renda(request, pessoa_id: int):
    pessoa = get_object_or_404(Pessoa, id=pessoa_id)
    print(pessoa)
    return ""

source/templates/base.html
{% load static %}

<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    {% block 'head' %}
    {% endblock %}
    <title>{% block 'title' %}{% endblock %}</title>
</head>

<header>
    {% block 'header' %}
    {% endblock %}
</header>

<body>     
    <nav id="sidebar">
        <div id="sidebar_content">
            <div id="user">
                <img id="user_avatar" src="{% static 'img/pessoas-default.png' %}">

                <p id="user_infos">
                    <span class="item-description">
                        Mikael Linhares
                    </span>
                    <span class="item-description">
                        Desenvolvedor
                    </span>
                </p>
            </div>

            <ul id="side_items">
            <li class="side-item" id="side-item-pessoas">
                <a href="{% url 'pessoas' %}">
                    <span class="material-icons bi pe-none me-2">groups</span>
                    <span class="item-description">
                        Pessoas
                    </span>
                </a>
            </li>

                <li class="side-item" id="side-item-propriedades">
                    <a href="{% url 'propriedades' %}">
                        <span class="material-icons bi pe-none me-2">home</span>
                        <span class="item-description">
                            Propriedades
                        </span>
                    </a>
                </li>

                <li class="side-item" id="side-item-metas">
                    <a href="#">
                        <span class="material-icons bi pe-none me-2">check_box</span>
                        <span class="item-description">
                            Metas
                        </span>
                    </a>
                </li>

                <li class="side-item" id="side-item-categorias">
                    <a href="#">
                        <span class="material-icons bi pe-none me-2">label</span>
                        <span class="item-description">
                            Categorias
                        </span>
                    </a>
                </li>

                <li class="side-item" id="side-item-despesas">
                    <a href="{% url 'despesas' %}">
                        <span class="material-icons bi pe-none me-2">credit_card_off</span>
                        <span class="item-description">
                            Despesas
                        </span>
                    </a>
                </li>

                <li class="side-item" id="side-item-pagamentos">
                    <a href="#">
                        <span class="material-icons bi pe-none me-2">credit_score</span>
                        <span class="item-description">
                            Pagamentos
                        </span>
                    </a>
                </li>
                
                <li class="side-item" id="side-item-rendas">
                <a href="#">
                    <span class="material-icons bi pe-none me-2">attach_money</span>
                    <span class="item-description">
                        Rendas
                    </span>
                </a>
            </li>
            </ul>

            <button id="open_btn">
                <span id="open_btn_icon" class="material-icons">arrow_forward</span>
            </button>
        </div>

        <div id="logout">
            <button id="logout_btn">
                <span class="material-icons">logout</span>
                <span class="item-description">
                    Logout
                </span>
            </button>
        </div>
    </nav>

    <!-- Mensagens -->
    <div id="display-mensagens">
        {% if messages %}
        {% for message in messages %}
        <div{% if message.tags %} class="alert {{ message.tags }}"{% endif %}>{{ message }}</div>
        {% endfor %}
        {% endif %}
    </div>

    <main>
    {% block 'body' %}
    {% endblock %}
    </main>

    {% block 'modal' %}
    {% endblock %}

    <script type="text/javascript" src={% static 'js/base.js' %}></script>
    {% block 'script' %}
    {% endblock %}
</body>

<footer>
    {% block 'footer' %}
    {% endblock %}
</footer>

</html>

source/templates/criar_despesa.html
{% extends 'base.html' %}
{% load static %}

{% block 'head' %}
<link rel="stylesheet" href="{% static 'css/criar_despesa.css' %}">
{% endblock %}

{% block 'script' %}
<script type="text/javascript" src={% static 'js/criar_despesa.js' %}></script>
<script>
    selecionarItemSidebar('side-item-despesas');
</script>
{% endblock %}

{% block 'title' %}
Criar Despesa
{% endblock%}

{% block 'body' %}
<form id="form-criar-despesa" method="POST">   
    {% csrf_token %}

    <h2>Nova Despesa</h2>

    <label for="input-nome">Nome</label>
    <div class="input-formulario">
        <input id="input-nome" name="nome" class="form-control" type="text" placeholder="Nome da despesa">
    </div>
    
    <label for="select-categoria">Categoria</label>
    <div class="input-formulario">
        <select id="select-categoria" name="categoria" class="custom-select" 
            onchange="selecionaCategoria(this.id)">
            <option value="" style="background-color: white; color: black;" disabled selected>Categoria da despesa</option>
            {% for categoria in categorias %}
            <option value="{{ categoria.id }}" style="background-color: {{ categoria.cor }};">{{ categoria.nome }}</option>
            {% endfor %}
        </select>
        <button type="button" class="btn btn-primary""><span class="material-icons">add</span></button>
    </div>
    
    <label for="group-valor">Valor</label>
    <div class="input-formulario">
        <div id="group-valor" class="input-group flex-nowrap">
            <div class="input-group-prepend"><span class="input-group-text">R$</span></div>
            <input id="input-valor" name="valor" type="number" min="0.01" step="0.01" class="form-control" placeholder="Valor">
        </div>
    </div>

    <label for="input-vencimento">Vencimento</label>
    <div class="input-formulario">
        <input id="input-vencimento" name="vencimento" class="form-control is-valid" type="date" placeholder="Vencimento" value="{{ hoje }}">
    </div>

    <label for="group-pagamento">Pagamento</label>
    <div class="input-formulario">
        <div id="group-pagamento" class="input-group flex-nowrap">
            <div onclick="alteraOpcaoPagamento()" style="cursor: pointer" class="input-group-prepend">
                <span id="bg-icone-pagamento" class="input-group-text bg-success">
                    <span id="icone-pagamento" class="material-icons bi pe-none me-2">check_box</span>
                </span>
            </div>
            <input id="descricao-pagamento" class="form-control" value="Com pagamento" disabled>
            <input id="input-pagamento" name="pagamento" type="hidden" value="true">
        </div>
    </div>

    <label id="label-pessoa" for="select-pessoa">Pagador</label>
    <div class="input-formulario">
        <select id="select-pessoa" name="pessoa" class="custom-select">
            <option value="" disabled selected>Pagador da despesa</option>
            {% for pessoa in pessoas %}
            <option value="{{ pessoa.id }}">{{ pessoa.nome }}</option>
            {% endfor %}
        </select>
        <button id="btn-add-pessoa" type="button" class="btn btn-primary""><span class="material-icons">add</span></button>
    </div>

    <label id="label-forma-pagamento" for="select-forma-pagamento">Forma de pagamento</label>
    <div class="input-formulario">
        <select id="select-forma-pagamento" name="forma_pagamento" class="custom-select">
            <option value="" disabled selected>Método de pagamento</option>
            {% for sigla, forma in formas_pagamento.items %}
            <option value="{{ sigla }}">{{ forma }}</option>
            {% endfor %}
        </select>
    </div>

    <button id="botao-salvar" class="btn btn-success" type="submit">Salvar</button>
</form>
{% endblock %}

source/templates/despesa_criar.html
{% extends 'base.html' %}
{% load static %}

{% block 'head' %}
<link rel="stylesheet" href="{% static 'css/despesa_criar.css' %}">
{% endblock %}

{% block 'script' %}
<script type="text/javascript" src={% static 'js/despesa_criar.js' %}></script>
<script>
    selecionarItemSidebar('side-item-despesas');
</script>
{% endblock %}

{% block 'title' %}
Criar Despesa
{% endblock%}

{% block 'body' %}
<form id="form-criar-despesa" method="POST">   
    {% csrf_token %}

    <h2>Nova Despesa</h2>

    <label for="input-nome">Nome</label>
    <div class="input-formulario">
        <input id="input-nome" name="nome" class="form-control" type="text" placeholder="Nome da despesa">
    </div>
    
    <label for="select-categoria">Categoria</label>
    <div class="input-formulario">
        <select id="select-categoria" name="categoria" class="custom-select" 
            onchange="selecionaCategoria(this.id)">
            <option value="" style="background-color: white; color: black;" disabled selected>Categoria da despesa</option>
            {% for categoria in categorias %}
            <option value="{{ categoria.id }}" style="background-color: {{ categoria.cor }};">{{ categoria.nome }}</option>
            {% endfor %}
        </select>
        <button type="button" class="btn btn-primary""><span class="material-icons">add</span></button>
    </div>
    
    <label for="group-valor">Valor</label>
    <div class="input-formulario">
        <div id="group-valor" class="input-group flex-nowrap">
            <div class="input-group-prepend"><span class="input-group-text">R$</span></div>
            <input id="input-valor" name="valor" type="number" min="0.01" step="0.01" class="form-control" placeholder="Valor">
        </div>
    </div>

    <label for="input-vencimento">Vencimento</label>
    <div class="input-formulario">
        <input id="input-vencimento" name="vencimento" class="form-control is-valid" type="date" placeholder="Vencimento" value="{{ hoje }}">
    </div>

    <label for="group-pagamento">Pagamento</label>
    <div class="input-formulario">
        <div id="group-pagamento" class="input-group flex-nowrap">
            <div onclick="alteraOpcaoPagamento()" style="cursor: pointer" class="input-group-prepend">
                <span id="bg-icone-pagamento" class="input-group-text bg-success">
                    <span id="icone-pagamento" class="material-icons bi pe-none me-2">check_box</span>
                </span>
            </div>
            <input id="descricao-pagamento" class="form-control" value="Com pagamento" disabled>
            <input id="input-pagamento" name="pagamento" type="hidden" value="true">
        </div>
    </div>

    <label id="label-pessoa" for="select-pessoa">Pagador</label>
    <div class="input-formulario">
        <select id="select-pessoa" name="pessoa" class="custom-select">
            <option value="" disabled selected>Pagador da despesa</option>
            {% for pessoa in pessoas %}
            <option value="{{ pessoa.id }}">{{ pessoa.nome }}</option>
            {% endfor %}
        </select>
        <button id="btn-add-pessoa" type="button" class="btn btn-primary""><span class="material-icons">add</span></button>
    </div>

    <label id="label-forma-pagamento" for="select-forma-pagamento">Forma de pagamento</label>
    <div class="input-formulario">
        <select id="select-forma-pagamento" name="forma_pagamento" class="custom-select">
            <option value="" disabled selected>Método de pagamento</option>
            {% for sigla, forma in formas_pagamento.items %}
            <option value="{{ sigla }}">{{ forma }}</option>
            {% endfor %}
        </select>
    </div>

    <button id="botao-salvar" class="btn btn-success" type="submit">Salvar</button>
</form>
{% endblock %}

source/templates/despesa_pagamentos.html
<div class="display-pagamentos">
    <h2 class="titulo-pagamentos">Pagamentos</h2>

    <div class="content-pagamentos">
        {% if valor_pendente > 0 %}
            <div class="form-pagamento">
                {% csrf_token %}

                <div class="form-pagamento-group">
                    <label for="group-valor">Valor</label>
                    <div id="group-valor" class="input-group flex-nowrap">
                        <div class="input-group-prepend"><span class="input-group-text">R$</span></div>
                        <input id="input-valor" name="valor" type="number" min="0.01" step="0.01" class="form-control" placeholder="Valor" value="{{ valor_pendente_str }}">
                    </div>
                </div>

                <div class="form-pagamento-group">
                    <label id="label-forma-pagamento" for="select-forma-pagamento">Forma de pagamento</label>
                    <select id="select-forma-pagamento" name="forma_pagamento" class="custom-select">
                        <option value="" disabled selected>Método de pagamento</option>
                        {% for sigla, forma in formas_pagamento.items %}
                        <option value="{{ sigla }}">{{ forma }}</option>
                        {% endfor %}
                    </select>
                </div>

                <div class="form-pagamento-group">
                    <label id="label-pessoa" for="select-pessoa">Pagador</label>
                    <select id="select-pessoa" name="pessoa" class="custom-select">
                        <option value="" disabled selected>Pagador da despesa</option>
                        {% for pessoa in pessoas %}
                        <option value="{{ pessoa.id }}">{{ pessoa.nome }}</option>
                        {% endfor %}
                    </select>
                </div>

                <div class="form-pagamento-group">
                    <label for="input-data">Data do pagamento</label>
                    <input id="input-data" name="data" class="form-control" type="date" placeholder="Vencimento" value="{{ hoje }}">
                </div>

                <div class="form-pagamento-group">
                    <label for="input-vencimento">Descrição</label>
                    <input id="input-descricao" name="descricao" class="form-control" type="text" placeholder="Descrição...">
                </div>
                
                <button class="btn btn-success" onclick="pagarDespesa({{despesa_id}})">Pagar</button>
            </div>
        {% endif %}

        {% if pagamentos %}
            <div class="list-pagamentos">
                {% for pagamento in pagamentos %}
                <div class="card-pagamento">
                    <div class="infos-pagamento">
                        <span>R$ {{ pagamento.valor }}</span>
                        <span>{{ pagamento.get_forma_pagamento_display }}</span>
                        <span>{{ pagamento.data }}</span>
                        <span>{{ pagamento.pessoa }}</span>
                        <span>{{ pagamento.descricao }}</span>
                    </div>
                    <span class="cancelar-pagamento material-icons">close</span>
                </div>
                {% endfor %}
            </div>
        {% endif %}
    </div>
    <div class="acoes-pagamentos">
        <button class="btn btn-danger" onclick="fecharModal()">Fechar</button>
    </div>
</div>

source/templates/pagina_principal.html
{% extends 'base.html' %}
{% load static %}

{% block 'head' %}
<!-- <link rel="stylesheet" href="{% static 'css/pagina_principal.css' %}"> -->
{% endblock %}

{% block 'script' %}
<!-- <script type="text/javascript" src={% static 'js/pagina_principal.js' %}></script> -->
{% endblock %}

{% block 'title' %}
Contas Casa
{% endblock%}

{% block 'body' %}
<div style="width: 100%; height: 100%; display: flex; align-items: center; justify-content: center;">
    <h1>Seja bem-vindo(a) ao Contas Casa<h1>
</div>
{% endblock %}

source/templates/pessoas.html
{% extends 'base.html' %}
{% load static %}

{% block 'head' %}
<link rel="stylesheet" href="{% static 'css/pessoas.css' %}">
{% endblock %}

{% block 'script' %}
<script type="text/javascript" src={% static 'js/pessoas.js' %}></script>
<script>selecionarItemSidebar('side-item-pessoas')</script>
{% endblock %}

{% block 'title' %}
Pessoas
{% endblock%}

{% block 'body' %}
<div class="main-container">
  <h1>Pessoas</h1>
  <div class="container-pessoas">
    {% for pessoa in pessoas %}
      <div class="card-pessoa">
        <h2>{{ pessoa.nome }}</h2>
        <p class="display-saldo alert-{% if pessoa.saldo < 0 %}danger{% else %}success{% endif %}">
          R$ {{ pessoa.saldo_formatado }}
        </p>
        <div class="acoes-pessoa">
          <button class="btn btn-success">Renda</button>
          <button class="btn btn-dark">Histórico</button>
        </div>
      </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

source/templates/propriedade.html
{% extends 'base.html' %}
{% load static %}

{% block 'head' %}
<link rel="stylesheet" href="{% static 'css/propriedade.css' %}">
{% endblock %}

{% block 'script' %}
<script type="text/javascript" src={% static 'js/propriedade.js' %}></script>
<script>selecionarItemSidebar('side-item-propriedades')</script>
{% endblock %}

{% block 'title' %}
Propriedade
{% endblock%}

{% block 'body' %}
<div class="main-container">
    <div class="display-propriedade">
        <div class="display-informacoes">
            <h1>{{ propriedade.nome }}</h1>
            <p>{{ propriedade.descricao }}</p>
        </div>
        <img class="display-imagem" 
        src="{% if propriedade.imagem %}{{ propriedade.imagem.url }}
                {% else %}{% static 'img/propriedades-default.jpg' %}{% endif %}">
    </div>

    <div class="display-propriedade-informacoes">
        <div class="display-financeiro">Aqui vai um pequeno dashboard da propriedade</div>
        <div class="display-pessoas">
            {% for pessoa in propriedade.pessoas.all %}
            <div class="card-pessoa">
                <img class="pessoa-imagem" src="{% if pessoa.imagem %}{{ pessoa.imagem.url }}
                                                {% else %}{% static 'img/pessoas-default.png' %}{% endif %}">
                <div class="pessoa-informacoes">
                    <h4>{{ pessoa.nome }}</h4>
                    <span class="badge alert-success">R$ {{ pessoa.saldo }}</span>
                </div>
                <button class="pessoa-visualizar btn">
                    <span class="material-icons">visibility</span>
                </button>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}